before_script:
  - npm install
script:
  - npm test
  - npm run lint
  - npm run build -s
language: node_js
env:
  - PORT=3000
node_js:
  - "6.9.0"
deploy:
  provider: azure_web_apps
  skip_cleanup: true

  #Set up environment variables in repo's Travis CI settings
  #AZURE_WA_USERNAME
  #AZURE_WA_PASSWORD
  #AZURE_WA_SITE

  #Additional resources regarding deployments:
  #https://docs.travis-ci.com/user/deployment/azure-web-apps/
  #http://www.microsoft.com/developerblog/real-life-code/2015/09/30/travis-azure.html
