before_script:
  - npm install
script:
  - npm test
  - npm run lint
  - npm run build
language: node_js
env:
  - PORT=3000
node_js:
  - "6.9.0"
deploy:
  provider: azure_web_apps
  skip_cleanup: true
